### ISSUE TITLE
建议summer-boot-codegen name换一下

### ISSUE THREAD

**Issue by Jzow** [summer-os/summer-boot#37]
这个后面跟 mybtis 和 web2生成的crate name，有歧义，这个模块是做宏和属性宏的吗

**Comment by Jzow** [comment]
因为在summer-framework 里也有个代码生成的module

**Comment by Yangandmore** [comment]
好的，这个我晚上来弄

**Comment by Yangandmore** [comment]
建议用什么名字呢？目前准备把所有的过程宏放进去

**Comment by Jzow** [comment]
> 建议用什么名字呢？目前准备把所有的过程宏放进去

这个后期目标是宏处理吗，你可以想一个

**Comment by Yangandmore** [comment]
是的，我这边看了很多的项目，他们的过程宏处理都会放在xxxx-codegen或者xxxx-macro这样的包下面，所以我这边就用了summer-boot-codegen，如果这个会有冲突的话，那我这边用summer-boot-macro试一下，回头我把扫包的那个代码一起传上去

**Comment by Jzow** [comment]
macro是不错的，codegen 有歧义

**Comment by Yangandmore** [comment]
代码提交啦

**Comment by Yangandmore** [comment]
已完成测试
